### ISSUE TITLE
Need to create two cards for completing the home content.

### ISSUE THREAD

**Issue by mwshubham** [mwshubham/JetpackCompose#1]
https://github.com/mwshubham/JetpackCompose/blob/cb3f582b698b2c179ed3b364c969eb2bcb9c109d/app/src/main/java/com/example/jetpackcompose/ui/home/HomeBodyContent.kt#L70

**Comment by PGautam27** [comment]
Hey buddy.... could you precise on what you want.

**Comment by mwshubham** [comment]
Hi @PGautam27 Thanks for your message. However, I am maintaing this project anymore. Feel free to fork and continue as per your thoughts.
